server:
  port: 11002

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  #swagger ?? ??
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  profiles:
    active:
      - default
  data:
    rest:
      base-path: /

  # maria db
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:33306/shop
    username: root
    password: root
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  sql:
    init:
      platform: mariadb
      encoding: UTF-8